---
name: Lint

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      statuses: write ## Needed for Super Linter

    steps:
      - name: Checkout Code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Super-Linter
        uses: super-linter/super-linter@4ce20838b8ab83717e78138c5b3a1407148e0918 # v8.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SAVE_SUPER_LINTER_SUMMARY: true
          VALIDATE_BIOME_LINT: false
          VALIDATE_CSS: false
          VALIDATE_CSS_PRETTIER: false
          VALIDATE_GIT_COMMITLINT: false
          VALIDATE_GITLEAKS: false
          VALIDATE_GRAPHQL_PRETTIER: false
          VALIDATE_HTML: false
          VALIDATE_HTML_PRETTIER: false
          VALIDATE_JAVASCRIPT_ES: false
          VALIDATE_JAVASCRIPT_PRETTIER: false
          VALIDATE_JSON: false
          VALIDATE_JSON_PRETTIER: false
          VALIDATE_JSONC: false
          VALIDATE_JSONC_PRETTIER: false
          VALIDATE_JSX: false
          VALIDATE_JSX_PRETTIER: false
          VALIDATE_PYTHON_RUFF: false
          VALIDATE_PYTHON_RUFF_FORMAT: false
          VALIDATE_TSX: false
          VALIDATE_TYPESCRIPT_ES: false
          VALIDATE_TYPESCRIPT_PRETTIER: false
          VALIDATE_VUE: false
          VALIDATE_VUE_PRETTIER: false
          FIX_BIOME_FORMAT: true
          FIX_GITHUB_ACTIONS_ZIZMOR: true
          FIX_MARKDOWN_PRETTIER: true
          FIX_MARKDOWN: true
          FIX_NATURAL_LANGUAGE: true
          FIX_YAML_PRETTIER: true
